/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/AboutSection.vue')['default']
    ContactSection: typeof import('./components/ContactSection.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    ILogosJavascript: typeof import('~icons/logos/javascript')['default']
    ILogosNodejsIcon: typeof import('~icons/logos/nodejs-icon')['default']
    ILogosPython: typeof import('~icons/logos/python')['default']
    ILogosReact: typeof import('~icons/logos/react')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    ILucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    ILucideCheck: typeof import('~icons/lucide/check')['default']
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    ILucideCopy: typeof import('~icons/lucide/copy')['default']
    ILucideDatabase: typeof import('~icons/lucide/database')['default']
    ILucideExternalLink: typeof import('~icons/lucide/external-link')['default']
    ILucideGithub: typeof import('~icons/lucide/github')['default']
    ILucideGlobe: typeof import('~icons/lucide/globe')['default']
    ILucideMail: typeof import('~icons/lucide/mail')['default']
    ILucideMenu: typeof import('~icons/lucide/menu')['default']
    ILucideMonitor: typeof import('~icons/lucide/monitor')['default']
    ILucideMoon: typeof import('~icons/lucide/moon')['default']
    ILucideNetwork: typeof import('~icons/lucide/network')['default']
    ILucideServer: typeof import('~icons/lucide/server')['default']
    ILucideSettings: typeof import('~icons/lucide/settings')['default']
    ILucideSmartphone: typeof import('~icons/lucide/smartphone')['default']
    ILucideSun: typeof import('~icons/lucide/sun')['default']
    ISkillIconsCs: typeof import('~icons/skill-icons/cs')['default']
    LanguageToggle: typeof import('./components/LanguageToggle.vue')['default']
    ProjectsSection: typeof import('./components/ProjectsSection.vue')['default']
    TechnologiesSection: typeof import('./components/TechnologiesSection.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
